version: "3.8"
services:
  auth:
    image: auth:0.0.1
    environment:
      NODE_ENV: production
      PORT: 4002
    build:
      context: auth/
      target: prod
    ports:
      - 4002:4002
    depends_on:
      - auth-mongo
  meetings:
    image: meetings:0.0.1
    environment:
      NODE_ENV: production
      PORT: 4000
    build:
      context: meetings/
      target: prod
    ports:
      - 4000:4000
    depends_on:
      - meetings-mongo
    
  analysis:
    image: analysis:0.0.1
    environment:
      NODE_ENV: production
      PORT: 4004
    build:
      context: analysis/
      target: prod
    ports:
      - 4004:4004

  auth-mongo:
    image: mongo
    ports:
      - 27017:27017

  meetings-mongo:
    image: mongo
    ports:
      - 6000:27017
