version: "3.8"
services:
  auth:
    image: edugaze.development:0.0.1
    environment:
      NODE_ENV: development
      PORT: 5000
    build:
      context: auth/
      target: prod
    ports:
      - 5000:3000
    volumes:
      - ./auth:/usr/src/app/
    depends_on:
      - auth-mongo
  meetings:
    image: edugaze.development:0.0.1
    environment:
      NODE_ENV: development
      PORT: 4000
    build:
      context: meetings/
      target: prod
    ports:
      - 4000:4000
    volumes:
      - ./meetings:/usr/src/app/
    depends_on:
      - meetings-mongo

  auth-mongo:
    image: mongo
    ports:
      - 27017:27017

  meetings-mongo:
    image: mongo
    ports:
      - 6000:27017
