version: "3.8"
services:
  my-service:
    image: edugaze.development:0.0.1
    environment:
      NODE_ENV: development
      PORT: 5000
    build:
      context: auth/
      target: dev
    ports:
      - 5000:3000
    volumes:
      - .:/usr/src/app
